name: webviewtube
description: Play YouTube videos on mobile platforms, using WebView and IFrame Player API.
version: 2.2.0
repository: https://github.com/yh-luo/webviewtube

environment:
  sdk: ">=2.17.0 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  webview_flutter: ^4.0.1
  webview_flutter_android: ^3.7.1
  webview_flutter_wkwebview: ^3.4.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  webview_flutter_platform_interface: ^2.3.1
